version: "3.1"
networks:
  support:
      driver: bridge
services:
    app:
      user: root
      container_name: app
      env_file: .env
      build: 
        context: .
        dockerfile: dotnet.dockerfile
      ports: 
        - ${APP_PORT}:80
      depends_on:
        - database
      networks:
        - support
    database:
      container_name: database
      image: mysql:8.0
      ports:
        - ${DATABASE_PORT}:3306
      env_file: .env
      restart: always
      volumes:
        - volume-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DBPassword}
        MYSQL_DATABASE: ${DBName}
      networks:
        - support
volumes:
   volume-data: