version: "3.1"
networks:
  suport:
      driver: bridge
services:
    app:
      container_name: app
      env_file: .env
      build: 
        context: .
        dockerfile: dotnet.dockerfile
      ports: 
        - ${APP_PORT}:5000
      volumes:
        - '.:/app'
      depends_on:
        - database
      networks:
        - suport
    database:
      container_name: database
      image: mysql:8.0
      ports:
        - ${DATABASE_PORT}:3306
      env_file: .env
      restart: always
      volumes:
        - volume-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_DB_PASSWORD: ${DATABASE_PASSWORD}
      networks:
        - suport
volumes:
   volume-data: